[package]
name = "rusty-tax-break"
version = "0.1.0"
authors = ["Arkadiusz Piekarz <piekarzarkadiusz@gmail.com>"]
edition = "2018"

[dependencies]
chrono = { version = "0.4.19", default-features = false, features = ["clock"] }
gdk = { version = "0.13.2", default-features = false }
git2 = { version = "0.13.17", default-features = false }
glib = { version = "0.10.3", default-features = false }
gtk = { version = "0.9.2", default-features = false, features = ["v3_20"] }
num-traits = { version = "0.2.14", default-features = false }
pango = { version = "0.9.1", default-features = false }
to_trait = { version = "0.1.1", default-features = false }
zip = { version = "0.5.10", default-features = false, features = ["deflate"] }

[dev-dependencies]
color-backtrace = { version = "0.5.0", default-features = false }
gtk-test = {version = "0.6.1", default-features = false }
rusty-fork = { version = "0.3.0", default-features = false }
tempfile = { version = "3.2.0", default-features = false }
termcolor = { version = "1.1.2", default-features = false }

[profile.release]
codegen-units = 1
lto = "fat"
incremental = false
